jobs:
  - name: feature-engineering
    countries: [spain]
    script: /p/projects/eubucco/git-eubucco/database/feature-engineering/fts.py
    data_dir: /p/projects/eubucco/data/2-database-city-level-v0_1
    log_dir: /p/tmp/floriann/feature-engineering/spain-demo
    properties:
      left_over: ''
      log_level: INFO
    resources:
      cpus: 1
      time: "06:00:00"
    special_cases:
      - name: tiny-cities
        file:
          type: geom.csv
          file_size_max: 10000000
        resources:
          cpus: 1
          time: "01:00:00"
      - name: small-cities
        file:
          type: geom.csv
          file_size_min: 10000000
          file_size_max: 20000000
        resources:
          cpus: 1
          time: "03:00:00"
      - name: medium-cities
        file:
          type: geom.csv
          file_size_min: 20000000
          file_size_max: 100000000
        resources:
          cpus: 4
          time: "12:00:00"
      - name: large-cities
        file:
          type: geom.csv
          file_size_min: 100000000
        resources:
          cpus: 8
          time: "24:00:00"

properties:
  conda_env: "/home/nikolami/.conda/envs/ox112"
  account: eubucco
  log_level: WARN
  exp_backoff_factor: 4
  max_retries: 3
  poll_interval: 30
  slack:
    channel: "#eubucco-ml-thesis"
    token: <to be added>
