jobs:
#  - name: streets-downloading
#    script: /p/projects/eubucco/other_projects/urbanformvmt_global/xml4uf_global/xml4uf/downloading/download_streets.py
#    data_dir: /p/projects/eubucco/other_projects/urbanformvmt_global/data
#    log_dir: /p/tmp/fewagner/xml4uf/streets_download
#    properties:
#      left_over: ''
#    resources:
#      cpus: 1
#      time: "00:30:00"
#      partition: io

  - name: preprocessing
    script: /p/projects/eubucco/other_projects/urbanformvmt_global/xml4uf_global/xml4uf/preprocessing/od_to_street.py
    data_dir: /p/projects/eubucco/other_projects/urbanformvmt_global/data
    log_dir: /p/tmp/fewagner/xml4uf/preprocessing
    properties:
      left_over: ''
    resources:
      cpus: 5
      time: "07:00:00"

properties:
  conda_env: "/home/fewagner/.conda/envs/xml4uf_env"
  account: eubucco
  custom_workfile: 'params_preprocessing.yml'
  log_level: WARN
  exp_backoff_factor: 4
  max_retries: 1
  poll_interval: 30
  slack:
    channel: "#test-slurm-bot"
    token: xoxb-2181800768432-3591454355235-XxTRN4mQidN8x81UmlFg860b
